### ISSUE TITLE
Rename src-d/gitbase-playground to src-d/gitbase-web

### ISSUE THREAD

**Issue by bzz** [src-d/gitbase-web#218]
- [x] Change repository name. (related: #223)
- [x] Travis CI sync
- [x] Update README/CONTRIBUTING. #220.
- [x] Rename binary [`gitbase-playground`](https://github.com/src-d/gitbase-playground/tree/master/cmd/gitbase-playground) -> `gitbase-web` #221 & #225.
- [ ] Check links from documentation of other projects.
- [x] Create srcd/gitbase-web on Docker Hub.
- [x] Push older images to srcd/gitbase-web.
- [x] Cur a release: push images to srcd/gitbase-web Docker Hub. [v0.1.3](https://github.com/src-d/gitbase-web/releases/tag/v0.1.3)
- [x] Update srcd/gitbase-playground description on Docker Hub to point to srcd/gitbase-web.
- [x] Coordinate update of the [src-d/charts/gitbase-playground](https://github.com/src-d/charts/tree/master/gitbase-playground). #222 & https://github.com/src-d/charts/pull/65
- [x] Setup drone for the new repository name https://github.com/src-d/issues-infrastructure/issues/214
- [x] Decide if we want to change the staging url, and open an issue for it.

Before doing any of the changes, let's double check that the task list is comprehensive.

**Comment by bzz** [comment]
@smola can help handing administrative part of renaming.

@carlosms could you please help with other parts of it?

**Comment by carlosms** [comment]
:+1: Off the top of my head I don't see anything missing.

**Comment by carlosms** [comment]
I updated the description to include links to each PR.

Regarding "Check links from documentation of other projects". I couldn't find any links to this repository in any other projects. Please @bzz also take a look in case I missed something.

**Comment by bzz** [comment]
> Regarding "Check links from documentation of other projects".

@carlosms I belive it's https://docs.sourced.tech/intro/#getting-started-with-gitbase-and-gitbase-playground but IDK which repository is that hosted in. 

@eiso could you please give us a hand here?

**Comment by carlosms** [comment]
Linking a question by @rporres for visibility here:
https://github.com/src-d/gitbase-web/pull/222#issuecomment-413908730
[Regarding staging url]
> I don't know if you want to change the name or not, most likely yes, but I have received no issue around this. So before I approve this change I would need to know what you want to do with the gitbase playground domain

**Comment by eiso** [comment]
@bzz I'll have a look through the documentation myself.

**Comment by carlosms** [comment]
I've added a new checkbox in the issues description to decide if we want to change the staging url or not. @eiso I guess you'll want to consider it.

**Comment by eiso** [comment]
@carlosms no need to change the staging URL. When we'll deploy it to production it will also be called a playground.

The rule of thumb we're following is that it is a web client but when we expose it with data online it becomes a playground for people.

**Comment by bzz** [comment]
Yes, please let's not change staging URL in this issue.

@eiso as there are no actionable items left here for App team, do you think we should close it?
Or keep it open until you take care of docs update?

**Comment by eiso** [comment]
This is not completed yet but feel free to close the issue, it's on my task list now.
