### ISSUE TITLE
Update to bblfsh client v3, use UASTv2, add option to choose UAST mode

### ISSUE THREAD

**Issue by carlosms** [src-d/gitbase-web#248]
- [x] gitbase 0.16 made `semantic` UAST the new default. Previously the format was `annotated`. We should also switch to `semantic` for consistency.
- [x] Update to bblfsh/client-go v3, following the gitbase 0.18 beta changes #279
  - [x] Update Dockerfile dependencies #282 
  - [x] Update Travis dependencies #284 
- [x] Use newer uast-viewer release with support for UASTv2 #279
- [x] Add an option to choose the UAST mode (semantic, annotated, native). #283

**Comment by carlosms** [comment]
@ricardobaeta, should we have the same mode selector as in bblfsh web, https://github.com/bblfsh/web/pull/165?

**Comment by carlosms** [comment]
Will leave open until we merge the gitbase-0.18 branch into master.
